# -*- coding: utf-8 -*-
"""pymongodb_connection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136JZ9ByrbTkj35TPCAkslNYYcVZMGlf5
"""

# Import package
import pymongo

# Make connection
client = pymongo.MongoClient("mongodb://127.0.0.1:27017/")

import pyspark
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext

conf = pyspark.SparkConf().setMaster("local").setAppName("My First Spark Job").setAll([('spark.driver.memory', '40g'),('spark.executor.memory','50g')])
sc = SparkContext(conf=conf)
spark = SQLContext(sc)

# MongoDB Details
mongo_ip = "mongodb://127.0.0.1:27017/newsDb."
# mongo_replica_set_name = "?replicaSet=rs0"

df = spark.read.format('com.mongodb.spark.sql.DefaultSource').option("uri", mongo_ip + "news").load()
df.createOrReplaceTempView("df")
df= spark.sql("SELECT * FROM df")
df.show()

!pip3 install pyspark

!pip install dnspython

!pip3 install "pymongo[srv]"

import pymongo
import pyspark

from pyspark.sql import SparkSession


con = pymongo.MongoClient("mongodb+srv://dayakar:3292%40wtt@clustertest.lgfcs.mongodb.net/newsDb?retryWrites=true&w=majority")
spark = SparkSession \
    .builder \
    .appName("myApp") \
    .config("spark.mongodb.input.uri", con ) \
    .config("spark.mongodb.output.uri", con) \
    .getOrCreate()

df = spark.read.format("mongo").option("uri",
"mongodb://127.0.0.1/people.contacts").load()