# -*- coding: utf-8 -*-
"""Dayakar_Krupa_Capstone_Milestone1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nH__Z_AkP6k3njfkbclgs25_MWUPxUYM

# Steps
 * Install json and requests, mongodb and mongosrv libraries
 * incase you want to scrap the data using beautiful soup install bs4
  * !pip3 install requests -- required for data extraction 
  * !pip3 install bs4 -- webscraping package
  * !pip3 install json - used for json convertion 
  * !pip3 install pymongo pymongo[srv]
 * convert the json string to json object - this important step
 *
"""

import json
import requests

import requests

url = "https://free-news.p.rapidapi.com/v1/search"

querystring = {"q":"Elon Musk","lang":"en"}

headers = {
    'x-rapidapi-host': "free-news.p.rapidapi.com",
    'x-rapidapi-key': "b593c9a319msh312e606d9a8f636p1ac2a1jsn57d0059e91f6"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

json_string = response.text

# Converting json string to json object

print(json_string)
print("The type of object is: ", type(json_string))
stud_obj = json.loads(json_string)
print(stud_obj)
print("The type of object is: ", type(stud_obj))
json_obj = json.dumps(stud_obj)
print(json_obj)
print("The type of object is: ", type(json_obj))

title = stud_obj["articles"][0]['title']
print(title)

len(stud_obj["articles"][0]['title'])

#declare empty var to append data
news_ls = []

for item in stud_obj['articles']:
  item_title = {}
  item_title['title'] = item['title']
  item_title['link'] = item['link']
  item_title['topic'] = item['topic']
  item_title['pub_date'] = item['published_date']
  item_title['summary'] = item['summary']
  news_ls.append(item_title)
  # print(item['title'])

news_ls[1]

#import pandas to create dataframe and CSV
import pandas as pd
df = pd.DataFrame(news_ls,columns=['title','summary','link','pub_date','topic'])

df.head()

"""# Mongodb

# Once the installation of pymongo and pymongo[srv] restart the runtime ***
"""

!pip3 install pymongo pymongo[srv]

import pymongo
from pymongo import MongoClient

!pip3 install "pymongo[srv]"

!pip install dnspython

# Load csv dataset
# data = pd.read_csv('BBCdata1.csv')
# Connect to MongoDB
# client =  MongoClient("mongodb+srv://Dayakar:<3292%40wtt>@clustertest-icsum.mongodb.net/test?retryWrites=true&w=majority")
# client = pymongo.MongoClient("mongodb+srv://dayakar:3292%40wtt@clustertest.lgfcs.mongodb.net/newsDb?retryWrites=true&w=majority")
# db = client.test
db = client['newsDb']
collection = db['news']
df.reset_index(inplace=True)
data_dict = df.to_dict("records")
# Insert collection
collection.insert_many(data_dict)